name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  schedule:
    - cron: '*/5 * * * *'

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.4']
    name: integration-tests (PHP ${{ matrix.php-versions }})
    steps:
      - uses: actions/checkout@v1
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-${{ matrix.php-version }}-composer-${{ matrix.dependencies }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.php-version }}-composer-${{ matrix.dependencies }}-

      - name: Install dependencies
        run: |
          composer update --prefer-dist --no-progress
      - name: Amogus
        run: |
      - name: Run script
        run: |
          php index.php
        env:
          OCI_REGION: ${{ secrets.OCI_REGION }}
          OCI_USER_ID: ${{ secrets.OCI_USER_ID }}
          OCI_TENANCY_ID: ${{ secrets.OCI_TENANCY_ID }}
          OCI_KEY_FINGERPRINT: ${{ secrets.OCI_KEY_FINGERPRINT }}
          OCI_PRIVATE_KEY_FILENAME: ${{ "-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDQQXsR23z1xWma
VJDxEXp5Ov4U2sucvWoYB11tfCq0+VdWp1o5J4IYe7HsA0t1uGa9ZQ3fKRY+7vbq
idt1pPbTjJXMLNfvRghO29kZXSjFt2rIavmjLCslF0zTR4VVKH0+fwT5QPMnRl7+
GhiG28v3bRb8dXat495IuVTRzlMjcZBKuVT09fqV8598km43zby40YjPA7X5t5d+
V3rCXdQTbBrmexxOlZgbFKUATXCfHeY7NFd2cLLAXcopoCuOlZ/LnETLl4aIfTpo
onbtLkQxtKYSyl6WG0BZmqXxCWxluknL0bve6AOMY9idspr4t7F5gRlKqoBb7m5O
PCPP6tizAgMBAAECggEAAel5l+MUGIbDK4uqnjP8k/lcYaE8OYh5qi/P7Hq1dhGy
x65j3MUSlwDBVCF+acQs8ucz6eazXnxZX8ziBKH9/1igLw6biuxX+vvEvsyR3I+m
PaHRzSA3yZbkEy220sUIGIp+mrIKD92/1VIBaj30kPIU9T6ecNLedK95UMkCqJju
YZM7w4V6oC7LUmpGl3AObXkaMChqt7wzVekINvWTi3P9vPyBAIGA1zS0wyWfXzPp
foKw3fYNs8AdGqx+nTYTnWyRIoevvfRaNDO3GUzw9Zx82ydl0xaT3DSmScStNySW
Z49mMZV4C9MPnikNsUVM61t+iXNDJg6XGyXj5XJCtQKBgQDqn7yXuqP5axO/Spsa
wvAU2xqkPAatGpq2sbgV4+SwRtVlSpcQCPSiXpUGQMoQclSp4HC3gd8AmtdM3xnX
+HB6/mZEoFJASjYzvedt6RI8zd8GDe/GxJ7WarfIjuAeGbafKN/LTrPI0jSLYU97
3fCmETZxfFBjHZydBXo/ZQM5zwKBgQDjOr6QECOREyATaq5bR33FghmS5w6zoShr
qk06EkFx/IXdZi3/gQVZVTgdFmYYjx3yRarqQuNFvMUi+JTXAk0gP7XTn+FjU87k
vAnqVWXn7RF1dIO5GGjSbv0IhILUb8B3TjvycUn1Ks0hO+5wBFvVIu+GLPmT2pMv
H+oqIpg/3QKBgC/3/p/q2dGJsdzfTPzYtCsfbL/9QcQsd0s45JEdKclcgg6WhHIT
0qhLvB4uKuHX7jVZHNJ36/b8sV4XEvqT4bNTxebr/EUGpzRG9EUFbOQflyRuvwId
evgNk4ueonWk/jBmM/MmIR3C1FlWyOBjTOs3A7GKIAlTqYx07Tx+030DAoGAGkDr
S5HRyi0/g37L7lfwPCWv9r0jgbWZCfd/PLpnPVhDzzTDE8ZAa/XgqduwqB3BBADw
omhgAeqxjDzUVZM6fgNearkKPYOtX9gp/R0ozQcjAUMZBQXA9q9EJPvKcekHf8FW
Q8i7Fsx/LtvRzLd0NMf4jLQdkeurHcK+N2gP1zECgYAQf6tCiXxB2GCoP09nbSQx
j2babaq1AHDkV6L5n4hts5KHD6PR/xLpf9xE1Hwa/5yUqqRn1EjEb6l5eVuj4cX0
wLxyc7BF/ZTTumKWGo1fTadcjrmfcTH10vrzTETQr4VOEnUZLKUTXNN91w7Wb4OV
cRHIxrauwBlXyG1MUsmT4A==
-----END PRIVATE KEY-----" }}
          OCI_AVAILABILITY_DOMAIN: ${{ secrets.OCI_AVAILABILITY_DOMAIN }}
          OCI_SUBNET_ID: ${{ secrets.OCI_SUBNET_ID }}
          OCI_IMAGE_ID: ${{ secrets.OCI_IMAGE_ID }}
          OCI_OCPUS: ${{ secrets.OCI_OCPUS }}
          OCI_MEMORY_IN_GBS: ${{ secrets.OCI_MEMORY_IN_GBS }}
          OCI_SHAPE: ${{ secrets.OCI_SHAPE }}
          OCI_MAX_INSTANCES: ${{ secrets.OCI_MAX_INSTANCES }}
          OCI_SSH_PUBLIC_KEY: ${{ secrets.OCI_SSH_PUBLIC_KEY }}
          TELEGRAM_USER_ID: ${{ secrets.TELEGRAM_USER_ID }}
          TELEGRAM_BOT_API_KEY: ${{ secrets.TELEGRAM_BOT_API_KEY }}
          AD_ALWAYS_FREE: ${{ secrets.AD_ALWAYS_FREE }}
          TEST_IMAGE_ID: ${{ secrets.TEST_IMAGE_ID }}
          TEST_SUBNET_ID: ${{ secrets.TEST_SUBNET_ID }}

